- name: TdAgent | get current version
  shell: >
    td-agent --version
  ignore_errors: yes
  changed_when: false
  register: current_tdagent

- name: TdAgent | Install | Download binary
  get_url:
    url: "{{ td_agent_path }}"
    dest: /tmp/tdagent.rpm
    checksum: "{{ td_agent_checksum }}"
  register: tdagent_download
  when: current_tdagent is failed or td_agent_version not in current_tdagent.stdout 

- name: TdAgent | Install | RPM
  yum:
    state: present
    name: "{{ tdagent_download.dest }}"
  when: current_tdagent is failed or td_agent_version not in current_tdagent.stdout 

- name: TdAgent | Config | fix td permissions
  file: 
    path: "{{ item }}"
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750
  with_items:
    - /etc/td-agent/conf.d
    - /etc/td-agent

- name: TdAgent | Config | Copy Configuration
  template: 
    src: "etc_td-agent_td-agent.conf"
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: 0440

- name: TdAgent | Config | Copy hostname filter
  copy: 
    src: "etc_tdagent_confd_filtername.conf"
    dest: /etc/td-agent/conf.d/filtername.conf
    owner: td-agent
    group: td-agent
    mode: 0440
  when: addhostname

# - name: TdAgent | install | Install build requirements
#   package:
#     name: "{{ item }}"
#     state: present
#   with_items: "{{ fluentd_build }}"

- include: syslog.yml
  when: configure_syslog

- name: TdAgent | plugins | Install gems
  command: "td-agent-gem install {{ item }}"
  with_items: "{{ fluentd_requirements }}"